### ISSUE TITLE
Use default waitset properties for latency and throughtput test

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#118]
**Description**
Set the DDS_WaitSetProperty_t of the waitset:

- If latency test: max_event_count and max_event_delay should be set to the minimum
- If throughput test: max_event_count and max_event_delay should use the default values of RTI Perftest.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
Although the idea is good, we would need to differentiate if this is a latency test or a throughput test in the Subscriber side of *RTI Perftest*. At this point, this information is not available.
