### ISSUE TITLE
Avoid template calling ParameterManager 

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#127]
**Description**

As a try of remove the neessity of template when ``get`` function of parameter manager is called, for example

``
_PM.get<bool>("keyed")
``

I suggest the following implementation.
``
_PM["keyed"]
``

This would be possible if we created a new operator
```
AnyParameter& operator[](std::string parameterKey)
{
    std::map<std::string, AnyParameter>::iterator it = _parameterList.find(parameterKey);
    return it->second;
}
```

And overload all the operators that it's been used with the corresponding type on the code on `AnyParameter` class.
For example:
```
operator bool() const
{
    return get<bool>()->get_value();
}

bool operator==(long long int var)
{
    if (_param->get_type() == T_NUMERIC_LLU) {
        return (long long int)get<unsigned long long>()->get_value() == var;
    } else if (_param->get_type() == T_NUMERIC_LD) {
        return get<long>()->get_value() == var;
    } else if (_param->get_type() == T_NUMERIC_D) {
        return get<int>()->get_value() == var;
    } else if (_param->get_type() == T_BOOL) {
        return get<bool>()->get_value() == var;
    } else {
        return false;
    }
}
```

The problem with this implementation is we would need to overload all the operators and all the types that we are using.
```
bool operator==(int var);
bool operator==(unsigned int var);
bool operator==(long var);
....
```

So, is something possible but may not worth it.
I will left this issue open if on a future release is something to reconsider.

**Comment by javmorcas** [comment]
@alfonso-soto, can you discuss this with @alexcamposruiz to see if it is worth implementing it?

**Comment by javmorcas** [comment]
At this point, we are not implementing this, as it would imply writing a lot of code.
