### ISSUE TITLE
Reaching max samples

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#130]
**Description**
Error:
```
PRESWriterHistoryDriver_addWrite:!history full
WriterHistoryMemoryPlugin_getEntry:exceeded max entries
WriterHistoryMemoryPlugin_dropSingleInstanceSamples:writer history full
PRESWriterHistoryDriver_addWrite:!history full
```

**How to Reproduce**

```
./bin/x64Linux3gcc5.4.0/release/perftest_cpp -pub -sendQueueSize 10 -pubRate 30:spin -bestEffort -verbosity 2 -dataLen 64000
./bin/x64Linux3gcc5.4.0/release/perftest_cpp -useReadThread -waitsetEventCount 1 -best -dataLen 64000
```

The fix would be set the property resource_limits.max_samples to a higher number: 

```
dw_qos.resource_limits.max_samples = std::max(_SendQueueSize, GetInitializationSampleCount());
```
**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
`GetInitializationSampleCount()` is already trying to do the max between `initialSampleCount` and `_sendQueueSize`, therefore, it will be always equal or greater than `_sendQueueSize `.

Therefore the discussion would be if we should assign `GetInitializationSampleCount()`, or stay with _sendQueueSize.

**Comment by javmorcas** [comment]
Not fixing this issue, see #190
