### ISSUE TITLE
Multicast result

### ISSUE THREAD

**Issue by hsienyan** [rticommunity/rtiperftest#138]
I tested the performance with multicast. But I got a weird result.

Case 1 
Sub:./bin/x64Linux3gcc5.4.0/release/perftest_cpp -transport UDPv4  dataLen 4000000 -pubRate 200 -sub 
Pub:./bin/x64Linux3gcc5.4.0/release/perftest_cpp -transport UDPv4  -dataLen 4000000 -pubRate 200 -pub -multicast

In this case, I set the multicast at the publisher only, I got 5311 Mbps of throughput.

Case 2
Sub:./bin/x64Linux3gcc5.4.0/release/perftest_cpp -transport UDPv4   -dataLen 4000000 -pubRate 200 -sub -multicast
Pub:./bin/x64Linux3gcc5.4.0/release/perftest_cpp -transport UDPv4  -dataLen 4000000 -pubRate 200 -pub -multicast

In second case, I set the multicast at both publisher and subscriber. But I only got 96 Mbps of throughput.

Please explain why there are a huge difference between two cases.

Thank you.

**Comment by javmorcas** [comment]
@hsienyan, let me try to reproduce this scenario. I will let you know once I have more information.

**Comment by hsienyan** [comment]
thank you @javmorcas

**Comment by javmorcas** [comment]
Hey @hsienyan, I was able to do some testing. I believe I know that is going on for you:

You are testing within your same machine, if you don't use multicast (in both places), we are going to try to communicate via unicast, and the nic/OS is smart enough to find that you are sending things to yourself, therefore not sending them through the network. However, that optimization cannot be done when using multicast. This is an example within one linux machine:

**No multicast, same machine:**

```
perfuser@perf03~/trees/rtiperftest/develop/2.4 bin/x64Linux3gcc4.8.2/release/perftest_cpp -transport UDPv4 -datalen 4000000 -pubRate 200 -sub
RTI Perftest 2.4.0 (RTI Connext DDS 5.3.1)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Subscriber ID: 0
	Receive using: Listeners
	Domain: 1
	Dynamic Data: No
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Use Multicast: False

Waiting to discover 1 publishers ...
Waiting for data...

********** New data length is 4000000
Packets:      213  Packets/s:     164  Packets/s(ave):     164  Mbps:  5279.7  Mbps(ave):  5279.7  Lost:     0 (0.00%)
Packets:      380  Packets/s:     166  Packets/s(ave):     165  Mbps:  5343.6  Mbps(ave):  5311.6  Lost:     0 (0.00%)
```

**Multicast, same machine:**

```
perfuser@perf03~/trees/rtiperftest/develop/2.4 bin/x64Linux3gcc4.8.2/release/perftest_cpp -transport UDPv4 -datalen 4000000 -pubRate 200 -sub -multicast
RTI Perftest 2.4.0 (RTI Connext DDS 5.3.1)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Subscriber ID: 0
	Receive using: Listeners
	Domain: 1
	Dynamic Data: No
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Use Multicast: True

Waiting to discover 1 publishers ...
Waiting for data...

********** New data length is 4000000
Packets:       39  Packets/s:      29  Packets/s(ave):      29  Mbps:   959.9  Mbps(ave):   959.9  Lost:     0 (0.00%)
Packets:       69  Packets/s:      29  Packets/s(ave):      29  Mbps:   959.9  Mbps(ave):   959.9  Lost:     0 (0.00%)
```

However, if you test within 2 different machines, you should not see that difference:

**No multicast, 2 machines:**

```
perfuser@perf04~/trees/rtiperftest/develop/2.4 bin/x64Linux3gcc4.8.2/release/perftest_cpp -transport UDPv4 -datalen 4000000 -pubRate 200 -sub
RTI Perftest 2.4.0 (RTI Connext DDS 5.3.1)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Subscriber ID: 0
	Receive using: Listeners
	Domain: 1
	Dynamic Data: No
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Use Multicast: False

Waiting to discover 1 publishers ...
Waiting for data...

********** New data length is 4000000
Packets:       33  Packets/s:      29  Packets/s(ave):      29  Mbps:   959.9  Mbps(ave):   959.9  Lost:     0 (0.00%)
Packets:       62  Packets/s:      28  Packets/s(ave):      28  Mbps:   927.9  Mbps(ave):   943.9  Lost:     0 (0.00%)
```

**Multicast, 2 machines:**

```
perfuser@perf04~/trees/rtiperftest/develop/2.4 bin/x64Linux3gcc4.8.2/release/perftest_cpp -transport UDPv4 -datalen 4000000 -pubRate 200 -sub -multicast
RTI Perftest 2.4.0 (RTI Connext DDS 5.3.1)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Subscriber ID: 0
	Receive using: Listeners
	Domain: 1
	Dynamic Data: No
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Use Multicast: True

Waiting to discover 1 publishers ...
Waiting for data...

********** New data length is 4000000
Packets:       50  Packets/s:      29  Packets/s(ave):      29  Mbps:   959.9  Mbps(ave):   959.9  Lost:     0 (0.00%)
Packets:       80  Packets/s:      29  Packets/s(ave):      29  Mbps:   959.9  Mbps(ave):   959.9  Lost:     0 (0.00%)
```

Please, let me know if you can reproduce the same behavior I do.

Regards,
Javi

**Comment by javmorcas** [comment]
@hsienyan, just wondering if you had time to look at this, in case it is something else.

**Comment by hsienyan** [comment]
@javmorcas Sorry. I overlooked your email.
Yes,you are right. I got a similar results. thank you
