### ISSUE TITLE
TCP transport, a failure condition with -peer command line option for subscriber 

### ISSUE THREAD

**Issue by VictorGorin** [rticommunity/rtiperftest#142]
**Description**
When "-peer" option is present on the command line of the subscriber, it can't subscribe to a published topic.

**How to Reproduce**
I use two nodes: 10.20.2.118 (newton) and 10.20.2.119 (planck).
I can successfully run rtiperftest with UDP  (w/ and w/o  -peer option on the command line), but I can successfully run with TCP transport ONLY if I remove "-peer" option from the command line on the subscriber side.
Below are examples of 2 cases for TCP:
***************************************
*** TCP, subscriber w/o -peer command option
***************************************

[cmru@newton rtiperftest]$  ./bin/x64Linux3gcc4.8.2/release/perftest_cpp03 -sub -domain 104 -nic 10.20.2.118  -dataLen 262144 -transport TCP -transportServerBindPort 50118 
[cmru@planck rtiperftest]$ ./bin/x64Linux3gcc4.8.2/release/perftest_cpp03 -pub -nic 10.20.2.119 -peer 10.20.2.118 -domain 104 -latencyCount 1000 -sendQueueSize 50 -dataLen 262144 -executionTime 30 -noPrint -flowControl default -transport TCP -transportServerBindPort 50119

***************************************
*** TCP, subscriber w -peer command option
***************************************

[cmru@newton rtiperftest]$  ./bin/x64Linux3gcc4.8.2/release/perftest_cpp03 -sub -domain 104 -nic 10.20.2.118  **-peer 10.20.2.119** -dataLen 262144 -transport TCP -transportServerBindPort 50118 
[cmru@planck rtiperftest]$ ./bin/x64Linux3gcc4.8.2/release/perftest_cpp03 -pub -nic 10.20.2.119 -peer 10.20.2.118 -domain 104 -latencyCount 1000 -sendQueueSize 50 -dataLen 262144 -executionTime 30 -noPrint -flowControl default -transport TCP -transportServerBindPort 50119

I am attaching two perftest_qos_profiles.xml files that I used on each node (Newton and Planck).

**Expected behavior**

I expect both cases of the command line to work. I wonder whether there is a bug or some misunderstanding on my part.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
[perftest_qos_profiles-Newton.txt](https://github.com/rticommunity/rtiperftest/files/2847621/perftest_qos_profiles-Newton.txt)
[perftest_qos_profiles-Planck.txt](https://github.com/rticommunity/rtiperftest/files/2847622/perftest_qos_profiles-Planck.txt)

**Comment by javmorcas** [comment]
@VictorGorin, I think the problem is in the way in which you are setting the peer: As this is TCPv4, you must specify the addresses in this way

**TCP LAN DEFINING PEER IN BOTH PLACES**

- Publisher `-transport TCP -peer tcpv4_lan://<IP_SUB>:<PORT_SUB> -transportVerbosity 10 -transportServerBindPort <PORT_PUB>`
- Subscriber `-transport TCP -peer tcpv4_lan://<IP_PUB>:<PORT_PUB> -transportVerbosity 10 -transportServerBindPort <PORT_SUB>`

**TCP LAN DEFINING PEER IN JUST ONE PLACE**

- Publisher `-transport TCP -transportServerBindPort <PORT_PUB>`
- Subscriber `-transport TCP -peer tcpv4_lan://<IP_PUB>:<PORT_PUB> -transportServerBindPort <PORT_SUB>`

**Comment by VictorGorin** [comment]
I replaced **-peer 10.20.2.119** with **-peer tcpv4_lan://10.20.2.119:50119**
and **-peer 10.20.2.118** with **-peer tcpv4_lan://10.20.2.118:50118**  on the command lines and my test executed fine. Thanks for your answer.
