### ISSUE TITLE
Improve documentation for -allowInterfaces command line option to inform that using micro only the name of the interface is allow.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#197]
**Description**

Micro only allow the name of the interface to the allow_interface QoS.
In our documentation, we are requesting the IP for this option. This should be changed using Micro.

**TODO**:
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
@alfonso-soto, in the documentation, in the `-nic` option we specify this:

```
  When compiling against *RTI Connext DDS Micro*, this option should always use
  the name of the interface, not the ip address (which it is valid when compiling
  against *RTI Connext DDS Pro*).
```

**Comment by javmorcas** [comment]
Discussed with @alfonso-soto, we are also going to add to the Documentation for Micro the previously mentioned comment.
