### ISSUE TITLE
Populate sent samples with real data

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#210]
**Description**
We want to be able to sent real data, picked from a file or from a random generator, different than the default sequence of zeroes that we send currently.

This effort will be specially useful in order to test compression. Also, in order to test data corruption.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by hamidzr** [comment]
I have some changes for the traditional C++ part I'll push it to a feature branch so you can take a look. Then I can look into other languages

**Comment by hamidzr** [comment]
traditional c++ https://github.com/rticommunity/rtiperftest/compare/master...hamidzr:feature/210-populate-samples-real-data
- file operations could be defined on a separate module in `./srcCppCommon`
- any naming suggestions?

**Comment by javmorcas** [comment]
Hi @hamidzr, that is great, we will take a look, what about if we invite you to the performance meeting next week and we discuss the changes there, we can take the work from where you leave it or at least help you
