### ISSUE TITLE
Wrong version in dockerfile for perftest 3.0.1

### ISSUE THREAD

**Issue by sumeet-rti** [rticommunity/rtiperftest#227]
**Description**
Dockerfile for perftest 3.0.1 uses version 2.2

**How to Reproduce**
open Dockerfile, look at version information

**Expected behavior**
Dockerfile should reference version 3.0.1

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
@sumeet-rti, we just fixed and tested this. Thanks for creating the issue!
