### ISSUE TITLE
Governance file for RTPSSignWithOrigAuthEncryptData doesn't encrypt user data

### ISSUE THREAD

**Issue by grahonan** [rticommunity/rtiperftest#239]
**Description**
The name of the governance file for RTPSSignWithOrigAuthEncryptData implies that user data is encrypted, but the data_protection_kind is set to NONE. 

**How to Reproduce**
See the governance file, [here](https://github.com/rticommunity/rtiperftest/blob/master/resource/secure/signed_PerftestGovernance_RTPSSignWithOrigAuthEncryptData.xml).
**Expected behavior**
I expect the data_protection_kind should be set to ENCRYPT.

**Comment by javmorcas** [comment]
@grahonan, this issue should be fixed already in the master branch, it will also get into the release/3.0 branch for the next patch.
