### ISSUE TITLE
perftest_cs.exe does not honor numIter

### ISSUE THREAD

**Issue by warrendewitradiance** [rticommunity/rtiperftest#254]
**Description**
When I build and run perftest_cs.exe from source, it doesn't seem to recognize the "-numIter" parameter.

**How to Reproduce**
I run perftest_cs.exe with the following parameters in an otherwise default configuration:
`-pub -numIter 10000 -peer [TARGET_MACHINE_IP] -latencyTest -noPrint -datalen 200`

**Expected behavior**
Even with those flags specifying 10000 iterations, there are many more samples than requested:

```
Perftest Configuration:
        Reliability: Reliable
        Keyed: No
        Publisher ID: 0
        Latency count: 1 latency sample every 1
        Data Size: 200
        Batching: No (Use "-batchSize" to setup batching)
        Publication Rate: Unlimited (Not set)
        Number of samples: 10000000
        Receive using: Listeners
        Domain: 1
        Dynamic Data: No
        Asynchronous Publishing: No
        XML File: perftest_qos_profiles.xml
```

 The CPP version (perftest_cpp.exe) seems to respond as request.

**Comment by javmorcas** [comment]
I was not able to reproduce this issue in Master. We can reopen the issue if this happens again.
