### ISSUE TITLE
Should be able to increase max data size used with flatdata/zerocopy.  Currently hardcoded in build to 10 MB.

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#259]
**Description**
Currently, RTI_FLATDATA_MAX_SIZE=10485760 is hardcoded in the compiler command line parameters.

This limits the maximum size of data testable using flatdata and thus also zerocopy to 10 MB.

There are more and more customers testing much larger data sizes, e.g., 20 to 30 MB.

Request a way to change this parameter, either in the IDL or somewhere else with appropriate documentation.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
This issue will be handled in this Request #265
