### ISSUE TITLE
Difficult to test large data sizes (> 10 MB) with shared memory, flat data and/or zero copy

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#260]
**Description**

An increasing number of customers using perftest are testing larger sized data (e.g., > 10 MB).  I have seen customer test 4 scenarios:

1. Using UDPv4 between processes on same machine
2. Using SHMEM between processes on same machine
3. Using FLATDATA against case 1 and 2 above
4. Using SHMEM, FLATDATA and ZERO copy

Currently, 63000/65536 is hardcoded in a variety of places, IDL as well as source code that either

1. automatically configures perftest to use the LargeData Test data type with unbounded sequence 
and/or
2. automatically use asynchronous publish mode

For any test through SHMEM, there shouldn't be any need to fragment or use asynchronous publish mode as long as the message_size_max and receive_buffer_size of the SHMEM transport is configured correctly with/or without zero copy.

However, currently, you can't get perftest to be able to use synchronous publishing with a bounded sequence data type with shared memory transport, flat data, and/or zero copy without modifying a bunch of files, including IDL, QOS and source files.

**perftest.idl:**

```
const long MAX_SYNCHRONOUS_SIZE = 63000;
const long MAX_BOUNDED_SEQ_SIZE = 63000;
```
to
```
const long MAX_SYNCHRONOUS_SIZE = 31457280;
const long MAX_BOUNDED_SEQ_SIZE = 31457280;
```

**perfest_ZeroCopy.idl:**

```const long MAX_BOUNDED_SEQ_SIZE_cp = 63000;```
to
```const long MAX_BOUNDED_SEQ_SIZE_cp = 31457280;```

**perftest_qos_profiles.xml:**

1.  
```
        </receiver_pool>
             <buffer_size>65536</buffer_size>
        </receiver_pool>
```

to NOT SET at all.  Default the above will be automatically sized by the core.

2.  
```
            <element>
              <name>dds.transport.shmem.builtin.parent.message_size_max</name>
              <value>65536</value>
```

to, or automatically set to a size that can accommodate the max data length being tested through SHMEM so that no DDS fragmentation is required

```
              <value>10485760</value>
            </element>
```

3. 
```
            <element>
              <name>dds.transport.shmem.builtin.receive_buffer_size</name>
              <value>2097152</value>
            </element>
```
to NOT SET at all.  This value is being calculated (incorrectly) by the source code and so this parameter set in the QOS file is currently being ignored.

**Infrastructure_pro.cxx (as well as in corresponding language versions..):**

```
    /*
     * We choose the minimum between the flow Controller max fragment size and
     * the message_size_max - RTPS headers.
     */
    int fragmentSize = (std::min)(
            parentMsgSizeMax - COMMEND_WRITER_MAX_RTPS_OVERHEAD,
            flowControllerTokenSize);

```
to
```    fragmentSize = parentMsgSizeMax - COMMEND_WRITER_MAX_RTPS_OVERHEAD;```

I don't think that when testing only using shared memory that there should even be a fragment size set.  In any case, don't know why `flowControllerTokenSize` is used to calculate the fragment size or is itself hardcoded to (any reason not to let it be the default value of UNLIMITED?)

`    int flowControllerTokenSize = 65536;`

What is desired is the ability to allow a user to test shmem, shmem + flat data, shmem + flatdata + zero copy for data sizes 0 to large data (30 MB?) without having to modify any files, IDL, QOS or source code...so by introducing new command line parameters if needed, and get the best performance numbers possible, avoiding asynchronous publish mode as well as unbounded sequences in the data type.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
We have been discussing this issue and concluded that we need to ease the use of perftest for larger data sizes. We divided the issue in several tasks:

- Synchronous size will disappear and we will replace the mechanism to choose Asynchronous Publishing

Asynchronous decision will be done by querying the enabled transports values for the max_sample_size. 

Asynchronous threshold will be the Minimum of all the properties minus an overhead (just to give space for the headers).

Changes will be done initially in the XML for the message_size_max.

- Remove the receive_pool -> auto by default

Documentation will have a section on how to modify the values.

- In the xml we will comment out the receive_buffer_size and we will not override it if it is uncommented.
