### ISSUE TITLE
build.bat doesn't recognize "--customTypeFlatData" as documented in .rst

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#262]
**Description**

In build.sh, "--customTypeFlatData" should be capitalized as "--customTypeFlatdata" for build scripts to follow convention, also .rst file documents as "--customTypeFlatData".

Also suggest that the command line arguments to the build scripts should be made case insensitive for ease of use.

Also recommend that build.sh always builds flat version of customType, so customer forced to define both flat and normal versions of their data with the flat one named <username>_flatdata to simplify procedures.

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
- The documentation refers to FlatData as this "FlatData" (RTI Connext DDS User's Manual). I reviewed Perftest documentation and Build scripts and everything seems to be coherent.
- Creating a gitlab issue to request making build scripts case insensitive for input parameters (#263)
- We will evaluate the option of making FlatData mandatory for customTypes.
