### ISSUE TITLE
Enable different output formats

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#280]
**Description**
Right now we do not have a documented way to easily export the resulting data to an excel table or similar.

For this feature, a new command-line option should be created. A path and a name would be specified in order to generate a .csv file with the results. This will simplify how the resulting data is exported.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
feature/280/output-format

srcDoc/designDocuments/280-output-format.md
