### ISSUE TITLE
Setting -sleep to a high value doesn't seem to take effect

### ISSUE THREAD

**Issue by rgrti** [rticommunity/rtiperftest#299]
from #performance slack:

perftest_cpp.exe -pub -bestEffort -dataLen 10000 -transport UDPv4 -allowInterfaces 127.0.0.1 -latency 1 -sleep 30000 -writerStats -numIter 10

perftest_cpp.exe -sub -bestEffort -dataLen 10000 -transport UDPv4 -allowInterfaces 127.0.0.1

This takes ~40 seconds to send 10 samples, instead I expected each iteration to be spaced out 30 seconds apart

**Comment by javmorcas** [comment]
I can confirm this issue. I will work on it.

**Comment by javmorcas** [comment]
@rgrti. This issue has been resolved and it is in Master now. Thanks for reporting it.
