### ISSUE TITLE
Error checking sample consistency in Traditional C++

### ISSUE THREAD

**Issue by grahonan** [rticommunity/rtiperftest#317]
**Description**
The follow error prints continuously in publisher and subscriber apps:

```
Error checking sample consistency
DDS_SampleInfoSeq_get_reference:!assert index out of bounds
TestDataLarge_ZeroCopy_w_FlatData_tSeq_get_reference:!assert index out of bounds
DDS_DataReader_is_metp_data_consistent:ERROR: Bad parameter: sample
```

**How to Reproduce**
Use master with Connext 6.0.1

For master, start a publisher like this:
`./bin/x64Linux3gcc5.4.0/debug/perftest_cpp -useReadThread -transport SHMEM -zeroCopy -checkConsistency -pub`

Then start a subscriber:
`./bin/x64Linux3gcc5.4.0/debug/perftest_cpp -useReadThread -transport SHMEM -zeroCopy -checkConsistency`

**Expected behavior**
No errors checking sample consistency

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
@grahonan, please notify the customer that this issue is resolved and fixed in Master.
