### ISSUE TITLE
Android SDK support needs to be updated

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#345]
**Description**

Current supported Android SDK (used to create .apk) is 26.0.0.  However, what we have done is compatible with latest Android SDK (at least 26.1.1) version.  Need to update and change our build file to support latest SDK (hopefully can retain backward compatibility with older SDKs.

**How to Reproduce**

Building with Android SDK 26.1.1 gets following output:

>
> ./build.sh --platform arm64Android9.0clang8.0ndkr19b --compiler /home/jayhou/Android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++ --linker /home/jayhou/Android/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++
> And it will fail in the end at:
> android update project -n perftest_publisher -t android-28 -p objs/arm64Android9.0clang8.0ndkr19b/publisher
> *************************************************************************
> The "android" command is deprecated.
> For manual SDK, AVD, and project management, please use Android Studio.
> For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
> *************************************************************************
> Invalid or unsupported command "update project -n perftest_publisher -t android-28 -p objs/arm64Android9.0clang8.0ndkr19b/publisher"
>
> Supported commands are:
> android list target
> android list avd
> android list device
> android create avd
> android move avd
> android delete avd
> android list sdk
> android update sdk
> makefile_perftest_arm64Android9.0clang8.0ndkr19b:180: recipe for target 'perftestPublisher/publisher' failed
>

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
Hi @howard-rti, I believe this is something we will need to do at the Platform level, right? I mean, once RTI Connext DDS decide to support that version for the SDK, then RTI Perftest will make the changes accordingly.

**Comment by howard-rti** [comment]
No, this is in the build.sh script.  It's using a deprecated command that doesn't work for the latest SDK.  Maybe there's an alternative command that works for both old and new SDKs.  It has nothing to do with the Android libraries that we have for Connext, as far as I understand.
