### ISSUE TITLE
Build fails for QNX target when using --micro

### ISSUE THREAD

**Issue by Iceegan** [rticommunity/rtiperftest#351]
**Description**
PerfTest fails to build for QNX platforms when building with Micro.

**How to Reproduce**
`./build.sh --platform armv8QNX7.0.0qcc_gpp5.4.0 --micro`

Results in:
```
rtiperftest/srcCpp/CpuMonitor.cxx: In constructor ‘CpuMonitor::CpuMonitor()’:
rtiperftest/srcCpp/CpuMonitor.cxx:62:13: error: ‘stderr’ was not declared in this scope
     fprintf(stderr, "[WARNING] get CPU consumption feature is not available in this OS\n");
             ^
rtiperftest/srcCpp/CpuMonitor.cxx:62:90: error: ‘fprintf’ was not declared in this scope
     fprintf(stderr, "[WARNING] get CPU consumption feature is not available in this OS\n");
                                                                                          ^
gmake[3]: *** [CMakeFiles/perftest_publisher.dir/CpuMonitor.cxx.o] Error 1
gmake[2]: *** [CMakeFiles/perftest_publisher.dir/all] Error 2
gmake[1]: *** [CMakeFiles/perftest_publisher.dir/rule] Error 2
gmake: *** [perftest_publisher] Error 2
[ERROR]: Failure compiling code for C++.
```

**Expected behavior**
PerfTest builds successfully for QNX with Micro without any modifications.

I was able to successfully build with the following changes:

**Modified build.sh line 872 to the following:**

 ```
cmake_generate_command= "${CMAKE_EXE} CMAKE_BUILD_TYPE=${RELEASE_DEBUG} -G \"Unix Makefiles\" -B./perftest_build -H. -DRTIME_TARGET_NAME=${platform} -DPLATFORM_LIBS=\"m;socket;${additional_included_libraries}\" -DCMAKE_CXX_COMPILER=q++ -DCMAKE_CXX_FLAGS=\"-Vgcc/5.4.0,gcc_ntoaarch64le -Y_gpp ${CMAKE_CXX_FLAGS}\"
```
 
This modification does 4 things:

1. Changes the CMake C++ compiler to q++

1. Adds the following compiler flags:

-Vgcc/5.4.0,gcc_ntoaarch64le

-Y_gpp

3. Removes the dl and pthread platform libraries

4. Adds the socket platform library

 
**Changed a macro in srcCppCommon/ParameterManager.h for QNX compatibility**

 
On line 24:

 
`#define STRNCASECMP strcasecmp`

 
On line 26:

 
`#define IS_OPTION(str, option) (STRNCASECMP(str, option) == 0)`

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
I can confirm this is a buggy behavior that needs fo be fixed. Adding it to Jira, reference: PERF-194
