### ISSUE TITLE
The examples should comply with both Pro and Micro

### ISSUE THREAD

**Issue by franporcel** [rticommunity/rtiperftest#353]
**Description**
The examples on [this link](https://github.com/rticommunity/rtiperftest/blob/master/srcDoc/examples.rst) only contain _<ip_addr>_ when using the _-nic_ option. This is only accepted on Connext Pro. On Connext Micro, you need the name of the interface, instead. This is stated on the [documentation](https://github.com/rticommunity/rtiperftest/blob/master/srcDoc/command_line_parameters.rst) for the _-nic_ option.

The examples should be valid for both Pro and Micro. I propose we have the name of the interface instead of the _<ip_addr>_ in the examples.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
We will change [this|https://github.com/rticommunity/rtiperftest/blob/master/srcDoc/examples.rst#rti-connext-dds-micro] section to reflect that `-nic` needs the interface name instead of the IP. We will also add a note for this.

**Comment by javmorcas** [comment]
I reviewed this issue with @franporcel and I created PERF-213 in RTI's Jira. I am closing this issue.
