### ISSUE TITLE
Perftest should throw an error / warning if the IP address is provided instead of the name of the interface on Micro

### ISSUE THREAD

**Issue by franporcel** [rticommunity/rtiperftest#354]
**Description**
According to the [documentation](https://github.com/rticommunity/rtiperftest/blob/master/srcDoc/command_line_parameters.rst), Micro only accepts the name of the NIC for the _-nic_ option, not the actual IP address. However, Perftest doesn't show any warning or error if you provide the IP address. Instead, Perftest keeps on running and the DomainParticipant doesn't have any locators, resulting in a lack of communication with other participants.

I propose that Perftest should identify this and throw an error / warning.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
I reviewed this issue with @franporcel and I created PERF-212 in RTI's Jira. I am closing this issue.
