### ISSUE TITLE
Documentation doesn't explicitly state reported latency is one-way

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#359]
**Description**

In the docs, how latency is measured is described as a roundtrip time.  But it's never stated that what the test reports is actually roundtrip/2...i.e., one-way latency.  So customers have had to inquire exactly what is printed, one-way or round trip.

Request to make explicit statement that printed latency is one-way, as calculated from a roundtrip measurement divide by 2.  It would be good to make it clear that the latency is one-way in multiple places in the doc since you can't count on the customer reading the whole thing.

**How to Reproduce**

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
When you execute the test the output displays:

```
Intervals One-way Latency for 100 Bytes:
Length (Bytes), Latency (us), Ave (us), Std (us), Min (us), Max (us)
           100,          226,      223,      3.0,      220,      226
           100,          117,      188,     50.0,      117,      226
```

And the summary at the end:

```
One-way Latency Summary:
Length (Bytes), Ave (us), Std (us), Min (us), Max (us), 50% (us), 90% (us), 99% (us), 99.99% (us), 99.9999% (us)
           100,       38,     15.2,       18,     1086,       35,       53,       80,         386,          1086
```

Where else are you suggesting we add the One-way?

I can potentially add it the `Introduction->Overview`, right after this:

```
Overview

The publishing side of the test writes data as fast as it can. Every few samples (configured through the command line), it sends a special sample requesting an echo from the subscribing side. It uses this request -> echo exchange to measure round-trip latency.
```

Would that be ok?

**Comment by howard-rti** [comment]
Hi, 

While I agree that the output of Perftest clearly says that it's a "one-way" latency, the issue is that reading through the documentation, nowhere is "one-way or oneway or one way" latency mentioned...it's always referred to as "round-trip" or "roundtrip" latency.

So, yes, somewhere (perhaps multiple places), we should state explicitly that while a roundtrip measure is performed...the test reports a one-way latency which is simply roundtrip/2.

**Comment by javmorcas** [comment]
I added in the documentation a comment every time the RTT is mentioned saying that the one way latency is half RTT
