### ISSUE TITLE
Fix return code check for Semaphore operations

### ISSUE THREAD

**Issue by fercsrti77** [rticommunity/rtiperftest#47]
While reviewing perftest code I have noticed that we do not do the right check for the return code returned by the RTIOsapiSemaphore_take and RTIOsapiSemaphore_give operations. We assume that they return a boolean when in reality they return a RTIOsapiSemaphoreStatus

For example:

            if(!RTIOsapiSemaphore_take(_pongSemaphore, NULL))
            {
                fprintf(stderr,"Unexpected error taking semaphore\n");
                return false;
            }

Should be replaced with:

            if(RTIOsapiSemaphore_take(_pongSemaphore, NULL)
                    != RTI_OSAPI_SEMAPHORE_STATUS_OK)
            {
                fprintf(stderr,"Unexpected error taking semaphore\n");
                return false;
            }

The end consequence is that these operations would never fail as all possible return code are greater than 0

**Comment by javmorcas** [comment]
This issue will be addressed as part of the changes for #37 and included for the RTI Perftest 2.4 release, since we'll move all the logic of the semaphores to a different class.
