### ISSUE TITLE
Certs need renewal

### ISSUE THREAD

**Issue by oreccp** [rticommunity/rtiperftest#49]
Security certificates are expired.

**Comment by javmorcas** [comment]
This issue has been fixed for Master. We are evaluating if merging this change for 2.3.X and 2.0.X.

**Comment by javmorcas** [comment]
After discussing this issue with @fercsrti77 and @softwarejimenez, we decided that:

- For 2.3 we will merge these changes and release a patch with this and other minor fixes (Named as 2.3.2).
- For 2.0 we will update the release branch, adding the changes for the certificates, so if someone gets the files to compile against 5.2.5, everything will work.

**Comment by javmorcas** [comment]
Merged fix in release/2.3.

**Comment by javmorcas** [comment]
Merged fix in release/2.0
