### ISSUE TITLE
Evaluate the differences between BE and Reliable for a latency test

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#79]
Part of:  #67

In order to see if we want to use `Best Effort` or `RELIABLE` reliability by default for a `Latency test` we want to evaluate the impact of using that in different scenarios:

- Inside the same machine (developer machine).
- In 2 powerful machines (Use RTI's Performance Lab machines).
- In 2 machines with memory restrictions. (2 Raspberry Pi).

All these results should be tested:

- For `UDPv4`, `TCP` and `SHMEM`
- For `C++`, `C++PSM` and `JAVA`
- For `32`, `256`, `2048` , `8192` and `63000`

- Median, Max and Min

- The command line parameters should be:

Publisher: `-pub -datalen <length> -transport <transport> -nic <> (-peer <peer> for TCP) -latencyTest`
Subscriber: `-sub -transport <transport> -nic <> (-peer <peer> for TCP)`

Suggestion: Use the test automation framework @softwarejimenez is developing.

**TODO**:
- [x] Generate a table for each of combinations with the diff in `us` and `%`
- [ ] Discuss results and conclude if we want to change our default values. Expose here the conclusions.

**Comment by alfonso-soto** [comment]
[--- Doc with the full Result ---](https://docs.google.com/spreadsheets/d/1QRUPGdQMjZjhRwFlzpxFWTl4fWV43MCxxl-nSXBeiQ4/edit?usp=sharing)


Resume (performance machines perf03/perf04)(Average of C++, C++03, Java):

 Transport | UDP | TCP | SHMEM
-- | -- | -- | --
Avg Improve using BE vs Rel | 6.65% | 4.18% | 10.64%

As conclusion: The average improvement using *Best effort* face of *Reliability* is around the 7% taking into account all the languages. In some cases (C++/SHMEM) it is up to 15%.

The mayors improvements are given with a data length between 256Bytes and 2kB. So I propose to use *Best Effort*  for small data.
