### ISSUE TITLE
Code convention for RTI Perftest

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#86]
**Description**
Define a code convention for *RTI Perftest*. It will be describe for the three different languages ( Cpp, .Net and Java):
- Comment conventions
- Indent style conventions
- Line length conventions: *80 characters is the maximum.*
- Naming conventions
  - Branch name
  - Function / Method
  - variable: class data member, constant names,
  - File name
- Programming practices
    -  Create Issue (New feature/ fix bug)
    -  Create branch
    -  Create Pull request
    -  Merge into master
________________________________________________
# Comment conventions
```
/*
 *    @brief <description>.
 *    @param <parameter_name> \b <In or Out or InOut>. <description param.>
 *    @return <description>.
 */
```
________________________________________________

# Naming conventions
- **C++**
```

class MyClass {
public:
    int myVariable;
private:
    int _privateVariable;
public:
    void myAwesomeMethod() {};
private:
    void myOtherMethod() {};
}
ThisIsAFunction() {};
```

**Comment by javmorcas** [comment]
We discussed this, and we decided that we will continue using RTI's Code Conventions, we will extend them if needed.
